### ISSUE TITLE
How are FileFields supported in django-tastypie-mongoengine?

### ISSUE THREAD

**Issue by alok25** [wlanslovenija/django-tastypie-mongoengine#47]
I can see reference field, embedded document field, listfield of embedded document field, etc. but didn't see FileField. Is it supported?

**Comment by nim4n** [comment]
this is an example of tastypie code for filefield how can I do it in mongo backend?
http://django-tastypie.readthedocs.org/en/latest/fields.html#filefield

    class ExcelResource(MultipartResource, ModelResource):
        file_field = fields.FileField(attribute="file_field")

        class Meta:
            queryset = Excel.objects.all()
            resource_name = 'excel'
            authorization = DjangoAuthorization()
            authentication = MultiAuthentication(BasicAuthentication(), SessionAuthentication())
            always_return_data = True
            list_allowed_methods = ['post']
