### ISSUE TITLE
Bump supported mongoengine version to 0.8.4

### ISSUE THREAD

**Issue by prymitive** [wlanslovenija/django-tastypie-mongoengine#65]
Currently django-tastypie-mongoengine depends on `mongoengine>=0.8.1,<0.8.2`, can you bump that to 0.8.4? It seems to be working just fine with it. Are there any know issues with 0.8.4?

**Comment by kepler** [comment]
Seems like this has been fixed: https://github.com/MongoEngine/mongoengine/issues/381#issuecomment-97609685
